language: java
dist: trusty     
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
mvn test -B

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
